apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wraki
spec:
  capacity:
    storage: 300Mi  # 0.1Gi
  accessModes:
    - ReadWriteOnce  # MongoDB requires RWO access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Make sure this matches the StorageClass of your PVC
  hostPath:
    path: /mnt/data/mongo  # For local storage, adjust based on your environment
