apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: wraki
spec:
  serviceName: "mongodb-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "400m"
            memory: "400Mi"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.password }}
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.mongodb.storage.size }}
      storageClassName: standard  # Ensure this matches the storage class in your PersistentVolume
