apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: wraki
spec:
  replicas: {{ .Values.webnodb.replicas }}
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb-container
        image: {{ .Values.webnodb.image }}
        ports:
        - containerPort: {{ .Values.webnodb.port }}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-port
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: wraki
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
