apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: wraki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "400m"
            memory: "400Mi"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.password }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: wraki
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
